#!/usr/bin/env python3
"""
Generate Voice Conversion test pairs from LibriTTS test-clean metadata.

This script reads metadata generated by prepare_vc_metadata.py and randomly
generates test pairs for Voice Conversion evaluation, ensuring:
1. Source and target are from different speakers
2. Source duration: 5-20 seconds
3. Target duration: 3-15 seconds
4. Gender information is recorded for later analysis

Outputs:
- test_vc.tsv: Test pairs with gender information
- transcript_converted.tsv: Transcripts for WER evaluation (converted audio)
- transcript_source.tsv: Transcripts for baseline WER evaluation (source audio)
"""

import argparse
import logging
import os
import random
import sys
from typing import Dict, List, Tuple

import pandas as pd


def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate VC test pairs from metadata."
    )
    parser.add_argument(
        "--metadata-file",
        type=str,
        required=True,
        help="Path to metadata TSV file generated by prepare_vc_metadata.py",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="data/vc_test",
        help="Output directory for test files",
    )
    parser.add_argument(
        "--num-pairs",
        type=int,
        default=500,
        help="Number of test pairs to generate (default: 500)",
    )
    parser.add_argument(
        "--source-min-duration",
        type=float,
        default=5.0,
        help="Minimum duration for source audio (seconds, default: 5.0)",
    )
    parser.add_argument(
        "--source-max-duration",
        type=float,
        default=20.0,
        help="Maximum duration for source audio (seconds, default: 20.0)",
    )
    parser.add_argument(
        "--target-min-duration",
        type=float,
        default=3.0,
        help="Minimum duration for target audio (seconds, default: 3.0)",
    )
    parser.add_argument(
        "--target-max-duration",
        type=float,
        default=15.0,
        help="Maximum duration for target audio (seconds, default: 15.0)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: 42)",
    )
    parser.add_argument(
        "--balance-gender",
        action="store_true",
        help="Try to balance gender combinations (M2M, F2F, M2F, F2M)",
    )
    return parser


def load_metadata(metadata_file: str) -> pd.DataFrame:
    """Load metadata from TSV file."""
    df = pd.read_csv(metadata_file, sep="\t")
    logging.info(f"Loaded metadata with {len(df)} utterances")
    return df


def filter_candidates(
    df: pd.DataFrame,
    min_duration: float,
    max_duration: float,
) -> pd.DataFrame:
    """Filter candidates by duration."""
    filtered = df[
        (df["duration"] >= min_duration) & (df["duration"] <= max_duration)
    ].copy()
    logging.info(
        f"Filtered to {len(filtered)} candidates "
        f"(duration: {min_duration}-{max_duration}s)"
    )
    return filtered


def estimate_max_pairs(
    source_candidates: pd.DataFrame,
    target_candidates: pd.DataFrame,
    balance_gender: bool = False,
) -> int:
    """
    Estimate the maximum number of pairs that can be generated.
    
    This is a conservative estimate that assumes:
    - Each source can pair with any target from a different speaker
    - For balance_gender=True, we need to consider each gender combination separately
    """
    if balance_gender:
        max_pairs = 0
        for src_gender in ["M", "F"]:
            for tgt_gender in ["M", "F"]:
                src_pool = source_candidates[
                    source_candidates["gender"] == src_gender
                ]
                tgt_pool = target_candidates[
                    target_candidates["gender"] == tgt_gender
                ]
                
                if len(src_pool) == 0 or len(tgt_pool) == 0:
                    continue
                
                src_speakers = set(src_pool["speaker_id"].unique())
                tgt_speakers = set(tgt_pool["speaker_id"].unique())
                
                combo_max = min(len(src_pool), len(tgt_pool))
                
                if len(src_speakers) == 1 and len(tgt_speakers) == 1:
                    if src_speakers == tgt_speakers:
                        combo_max = 0
                
                max_pairs += combo_max
        
        return max_pairs
    else:
        src_speakers = set(source_candidates["speaker_id"].unique())
        tgt_speakers = set(target_candidates["speaker_id"].unique())
        
        if len(src_speakers) == 1 and len(tgt_speakers) == 1:
            if src_speakers == tgt_speakers:
                return 0
        
        return min(len(source_candidates), len(target_candidates))


def generate_test_pairs(
    source_candidates: pd.DataFrame,
    target_candidates: pd.DataFrame,
    num_pairs: int,
    seed: int,
    balance_gender: bool = False,
) -> List[Tuple[str, str, str, str, str, str]]:
    """
    Generate random test pairs.

    Returns:
        List of tuples: (wav_name, source_wav, target_wav, 
                        source_gender, target_gender, source_transcript)
    """
    random.seed(seed)
    test_pairs = []
    seen_pairs = set()  

    if balance_gender:
        pairs_per_combo = num_pairs // 4
        remainder = num_pairs % 4

        gender_combinations = [
            ("M", "M", pairs_per_combo + (1 if remainder > 0 else 0)),
            ("F", "F", pairs_per_combo + (1 if remainder > 1 else 0)),
            ("M", "F", pairs_per_combo + (1 if remainder > 2 else 0)),
            ("F", "M", pairs_per_combo),
        ]

        skipped_combos = []
        for src_gender, tgt_gender, count in gender_combinations:
            src_pool = source_candidates[
                source_candidates["gender"] == src_gender
            ].to_dict("records")
            tgt_pool = target_candidates[
                target_candidates["gender"] == tgt_gender
            ].to_dict("records")

            if len(src_pool) == 0 or len(tgt_pool) == 0:
                logging.warning(
                    f"⚠️  Not enough candidates for {src_gender}2{tgt_gender}: "
                    f"source={len(src_pool)}, target={len(tgt_pool)}. Skipping this combination."
                )
                skipped_combos.append(f"{src_gender}2{tgt_gender}")
                continue

            src_speakers = set([s["speaker_id"] for s in src_pool])
            tgt_speakers = set([t["speaker_id"] for t in tgt_pool])
            
            if len(src_speakers) == 1 and len(tgt_speakers) == 1:
                if src_speakers == tgt_speakers:
                    logging.warning(
                        f"⚠️  Cannot generate {src_gender}2{tgt_gender} pairs: "
                        f"source and target have the same speaker. Skipping."
                    )
                    skipped_combos.append(f"{src_gender}2{tgt_gender}")
                    continue

            combo_generated = 0
            for i in range(count):
                max_attempts = 100
                for attempt in range(max_attempts):
                    source = random.choice(src_pool)
                    target = random.choice(tgt_pool)

                    pair_key = (source["wav_path"], target["wav_path"])

                    if (source["speaker_id"] != target["speaker_id"] and 
                        pair_key not in seen_pairs):
                        seen_pairs.add(pair_key)
                        break
                else:
                    if combo_generated == 0:
                        logging.warning(
                            f"⚠️  Could not generate any valid pairs for {src_gender}2{tgt_gender} "
                            f"after {max_attempts} attempts. Skipping this combination."
                        )
                        skipped_combos.append(f"{src_gender}2{tgt_gender}")
                    else:
                        logging.warning(
                            f"⚠️  Could only generate {combo_generated}/{count} pairs for "
                            f"{src_gender}2{tgt_gender}. Stopping."
                        )
                    break

                wav_name = f"vc_{len(test_pairs):04d}_{src_gender}2{tgt_gender}"

                test_pairs.append(
                    (
                        wav_name,
                        source["wav_path"],
                        target["wav_path"],
                        source["gender"],
                        target["gender"],
                        source["transcript"],
                    )
                )
                combo_generated += 1
            
            if combo_generated > 0:
                logging.info(
                    f"✓ Generated {combo_generated}/{count} pairs for {src_gender}2{tgt_gender}"
                )
        
        if skipped_combos:
            logging.warning(
                f"⚠️  Skipped gender combinations: {', '.join(skipped_combos)}. "
                f"Final pair count may be less than requested."
            )

    else:
        src_pool = source_candidates.to_dict("records")
        tgt_pool = target_candidates.to_dict("records")

        for i in range(num_pairs):
            max_attempts = 100
            for attempt in range(max_attempts):
                source = random.choice(src_pool)
                target = random.choice(tgt_pool)

                pair_key = (source["wav_path"], target["wav_path"])

                if (source["speaker_id"] != target["speaker_id"] and 
                    pair_key not in seen_pairs):
                    seen_pairs.add(pair_key)
                    break
            else:
                logging.warning(
                    f"Could not find valid pair {i} after {max_attempts} attempts"
                )
                continue

            src_gender = source["gender"]
            tgt_gender = target["gender"]
            wav_name = f"vc_{i:04d}_{src_gender}2{tgt_gender}"

            test_pairs.append(
                (
                    wav_name,
                    source["wav_path"],
                    target["wav_path"],
                    source["gender"],
                    target["gender"],
                    source["transcript"],
                )
            )

    logging.info(f"Generated {len(test_pairs)} test pairs")
    return test_pairs


def save_test_files(test_pairs: List[Tuple], output_dir: str):
    """
    Save test files.

    Files generated:
    - test_vc.tsv: wav_name, source_wav, target_wav, source_gender, target_gender
    - transcript_converted.tsv: wav_name, transcript (for WER on converted audio)
    - transcript_source.tsv: wav_name, transcript (for baseline WER on source audio)
    """
    os.makedirs(output_dir, exist_ok=True)

    test_vc_path = os.path.join(output_dir, "test_vc.tsv")
    with open(test_vc_path, "w", encoding="utf-8") as f:
        for wav_name, source_wav, target_wav, src_gender, tgt_gender, _ in test_pairs:
            f.write(
                f"{wav_name}\t{source_wav}\t{target_wav}\t{src_gender}\t{tgt_gender}\n"
            )
    logging.info(f"Saved test pairs to {test_vc_path}")

    transcript_converted_path = os.path.join(output_dir, "transcript_converted.tsv")
    with open(transcript_converted_path, "w", encoding="utf-8") as f:
        for wav_name, _, _, _, _, transcript in test_pairs:
            f.write(f"{wav_name}\t{transcript}\n")
    logging.info(f"Saved converted transcripts to {transcript_converted_path}")

    transcript_source_path = os.path.join(output_dir, "transcript_source.tsv")
    with open(transcript_source_path, "w", encoding="utf-8") as f:
        for wav_name, _, _, _, _, transcript in test_pairs:
            f.write(f"{wav_name}_source\t{transcript}\n")
    logging.info(f"Saved source transcripts to {transcript_source_path}")


def print_statistics(test_pairs: List[Tuple]):
    """Print statistics about generated test pairs."""
    gender_combos = {}
    for _, _, _, src_gender, tgt_gender, _ in test_pairs:
        combo = f"{src_gender}2{tgt_gender}"
        gender_combos[combo] = gender_combos.get(combo, 0) + 1

    logging.info("=" * 60)
    logging.info("Test Pair Statistics:")
    logging.info(f"  Total pairs: {len(test_pairs)}")
    for combo, count in sorted(gender_combos.items()):
        percentage = count / len(test_pairs) * 100
        logging.info(f"  {combo}: {count} ({percentage:.1f}%)")
    logging.info("=" * 60)


def main():
    parser = get_parser()
    args = parser.parse_args()

    formatter = "%(asctime)s %(levelname)s [%(filename)s:%(lineno)d] %(message)s"
    logging.basicConfig(format=formatter, level=logging.INFO)

    if not os.path.isfile(args.metadata_file):
        logging.error(f"Metadata file not found: {args.metadata_file}")
        sys.exit(1)

    logging.info("Loading metadata...")
    metadata = load_metadata(args.metadata_file)

    logging.info(
        f"Filtering source candidates "
        f"(duration: {args.source_min_duration}-{args.source_max_duration}s)..."
    )
    source_candidates = filter_candidates(
        metadata, args.source_min_duration, args.source_max_duration
    )

    logging.info(
        f"Filtering target candidates "
        f"(duration: {args.target_min_duration}-{args.target_max_duration}s)..."
    )
    target_candidates = filter_candidates(
        metadata, args.target_min_duration, args.target_max_duration
    )

    if len(source_candidates) == 0 or len(target_candidates) == 0:
        logging.error("Not enough candidates after filtering!")
        sys.exit(1)

    max_possible = estimate_max_pairs(
        source_candidates, target_candidates, args.balance_gender
    )
    
    logging.info("=" * 60)
    logging.info("Pair Generation Capacity Check:")
    logging.info(f"  Requested pairs:     {args.num_pairs}")
    logging.info(f"  Estimated maximum:   ~{max_possible}")
    logging.info("=" * 60)
    
    if args.num_pairs > max_possible:
        logging.warning(
            f"⚠️  WARNING: Requested {args.num_pairs} pairs, but only ~{max_possible} pairs "
            f"are estimated to be possible with current constraints."
        )
        logging.warning(
            f"⚠️  The script will generate as many pairs as possible, but the final count "
            f"may be less than {args.num_pairs}."
        )
        logging.warning(
            f"⚠️  Consider reducing --num-pairs or relaxing duration constraints."
        )
    elif args.num_pairs > max_possible * 0.9:
        logging.warning(
            f"⚠️  Requested {args.num_pairs} pairs is close to the estimated maximum "
            f"(~{max_possible}). Some pairs may fail to generate."
        )
    else:
        logging.info(f"✓ Requested {args.num_pairs} pairs is within capacity (~{max_possible})")
    
    logging.info("")

    logging.info(f"Generating {args.num_pairs} test pairs (seed={args.seed})...")
    test_pairs = generate_test_pairs(
        source_candidates,
        target_candidates,
        args.num_pairs,
        args.seed,
        args.balance_gender,
    )

    if not test_pairs:
        logging.error("Failed to generate any test pairs!")
        logging.error("This may be due to:")
        logging.error("  1. Too strict duration constraints")
        logging.error("  2. Insufficient speaker diversity")
        logging.error("  3. Gender balance requirements too strict")
        sys.exit(1)
    
    if len(test_pairs) < args.num_pairs:
        logging.warning("=" * 60)
        logging.warning(
            f"⚠️  WARNING: Generated {len(test_pairs)} pairs, but {args.num_pairs} were requested."
        )
        logging.warning(
            f"⚠️  This is acceptable - evaluation will proceed with {len(test_pairs)} pairs."
        )
        logging.warning(
            f"⚠️  All evaluation scripts will use the actual generated pairs, not the requested count."
        )
        logging.warning("=" * 60)
    else:
        logging.info(f"✓ Successfully generated {len(test_pairs)} pairs as requested")

    print_statistics(test_pairs)

    logging.info(f"Saving test files to {args.output_dir}...")
    save_test_files(test_pairs, args.output_dir)

    logging.info("Done!")


if __name__ == "__main__":
    main()

