#!/usr/bin/env bash

# Voice Conversion data preparation script for LibriTTS-100h only
# Modified from prepare_libritts.sh to use only train-clean-100 subset

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
export PYTHONPATH=../../:$PYTHONPATH

set -eou pipefail

stage=0
stop_stage=3
sampling_rate=24000
nj=20

dl_dir=$PWD/download

. utils/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download data"

  # If you have pre-downloaded it to /path/to/LibriTTS,
  # you can create a symlink
  #
  #   ln -sfv /path/to/LibriTTS $dl_dir/LibriTTS
  #
  if [ ! -d $dl_dir/LibriTTS ]; then
    lhotse download libritts $dl_dir
  fi

fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare LibriTTS manifest (train-clean-100 and dev-clean only for VC)"
  # We assume that you have downloaded the LibriTTS corpus
  # to $dl_dir/LibriTTS

  # For VC, we only need train-clean-100 and dev-clean
  mkdir -p data/manifests
  if [ ! -e data/manifests/.libritts_vc.done ]; then
    lhotse prepare libritts --num-jobs ${nj} $dl_dir/LibriTTS data/manifests
    touch data/manifests/.libritts_vc.done
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Compute Fbank for LibriTTS VC (train-clean-100 and dev-clean only)"
  mkdir -p data/fbank

  if [ ! -e data/fbank/.libritts_vc.done ]; then
    # Only process train-clean-100 and dev-clean for VC training
    for subset in train-clean-100 dev-clean; do
      python3 -m zipvoice.bin.compute_fbank \
        --source-dir data/manifests \
        --dest-dir data/fbank \
        --dataset libritts \
        --subset ${subset} \
        --sampling-rate $sampling_rate \
        --num-jobs ${nj}
    done
    touch data/fbank/.libritts_vc.done
  fi

  # For VC training, we use train-clean-100 as training set
  # and dev-clean as validation set (no shuffling needed)
  if [ ! -f data/fbank/libritts_cuts_vc_train.jsonl.gz ]; then
    log "Creating VC training set from train-clean-100"
    cp data/fbank/libritts_cuts_train-clean-100.jsonl.gz data/fbank/libritts_cuts_vc_train.jsonl.gz
  fi

  if [ ! -f data/fbank/libritts_cuts_vc_dev.jsonl.gz ]; then
    log "Creating VC dev set from dev-clean"
    cp data/fbank/libritts_cuts_dev-clean.jsonl.gz data/fbank/libritts_cuts_vc_dev.jsonl.gz
  fi

  if [ ! -e data/fbank/.libritts_vc_validated.done ]; then
    log "Validating data/fbank for LibriTTS VC"
    python3 ./utils/validate_manifest.py \
      data/fbank/libritts_cuts_vc_train.jsonl.gz
    python3 ./utils/validate_manifest.py \
      data/fbank/libritts_cuts_vc_dev.jsonl.gz
    touch data/fbank/.libritts_vc_validated.done
  fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Generate token file for VC (character-based)"
  # For VC, we still need a token file for compatibility, 
  # but it won't be used since we use speech content encoder
  if [ ! -e data/tokens_libritts_vc.txt ]; then
    python3 ./local/prepare_token_file_char.py \
      --manifest data/fbank/libritts_cuts_vc_train.jsonl.gz \
      --tokens data/tokens_libritts_vc.txt
  fi
fi
